### ISSUE TITLE
Syntax error, won't compile

### ISSUE THREAD

**Issue by flarn2006** [JakeHL/NitroStream#3]
Error in README.md:

> String.Format(jlangford{0}outlook{1}com, "@", ".")

This is invalid code. The first argument should be in quotes; otherwise the code fails to compile. :p

**Comment by JakeHL** [comment]
Haha! You're right! I'm a fool!

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Aug 23, 2016 at 4:54 AM +0100, "flarn2006" <notifications@github.com<mailto:notifications@github.com>> wrote:


String.Format(jlangford{0}outlook{1}com, "@", ".")

This is invalid code. The first argument should be in quotes; otherwise the code fails to compile. :p

-
